image: "ubuntu:latest"

variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - apt-get update
    - apt-get install -y python3-pip git
    - pip3 install --user -r ./requirements.txt

build:
    script:
        - LC_ALL=C.UTF-8 LANG=C.UTF-8 ~/.local/bin/mkdocs build
    artifacts:
        paths:
            - site
        expire_in: 1 week

