image: "registry.labs.nic.cz/turris/user-docs"

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - test
    - deploy

test-compilation:
    stage: test
    script:
        - mkdocs build --strict

test-links:
    stage: test
    script:
        - ./test-links.sh

test-remote-links:
    stage: test
    allow_failure: true
    script:
        - ./test-links.sh --remote

deploy:
    stage: deploy
    script:
        - LC_ALL=C.UTF-8 LANG=C.UTF-8 mkdocs build
    artifacts:
        paths:
            - site
        expire_in: 1 week
