site_name: Turris Documentation
site_description: Official Turris documentation for both hardware and software
site_author: CZ.NIC z.s.p.o.
copyright: CC-BY-SA-4.0


theme:
    name: null
    custom_dir: 'material-turris/material/'
    logo: '/theme/turris-logo.svg'
    favicon: '/theme/favicon.ico'
    font: false
    language: 'en'
    palette:
        primary: "turris"
        accent: "turris"
    feature:
        tabs: false
    static_templates:
      - 404.html


markdown_extensions:
    - extra
    - codehilite
    - smarty
    - toc
    - wikilinks
    - admonition

plugins:
    - search:
        lang: ['en']
        prebuild_index: False


extra:
  social:
    - type: 'globe'
      link: 'https://turris.cz'
    - type: 'gitlab'
      link: 'https://gitlab.labs.nic.cz/turris'
    - type: 'github'
      link: 'https://github.com/CZ-NIC'
    - type: 'twitter'
      link: 'https://twitter.com/turris_cz'

nav:
- Introduction: 'index.md'
- Basics:
    - Applications:
        - 'Netmetr': 'basics/apps/netmetr.md'
    - First setup:
        - 'Mox': 'basics/first-setup/mox_first_setup.md'
        - 'Omnia': 'basics/first-setup/omnia.md'
- Hardware specific topics:
    - Mox:
        - 'Reset and rescue': 'hw-spec/mox/mox_rescue_modes.md'
        - 'MicroSD card Preparation': 'hw-spec/mox/mox_microsd.md'
        - 'CPU module only': 'hw-spec/mox/mox_cpu_only.md'

