site_name: Turris Documentation
site_description: Official Turris documentation for both hardware and software
site_author: CZ.NIC z.s.p.o.
copyright: CC-BY-SA-4.0


theme:
    name: null
    custom_dir: 'material-turris/material/'
    logo: '/theme/turris-logo.svg'
    favicon: '/theme/favicon.ico'
    font: false
    language: 'en'
    palette:
        primary: "turris"
        accent: "turris"
    feature:
        tabs: false
    static_templates:
      - 404.html


markdown_extensions:
    - markdown_include.include:
        base_path: docs
    - admonition
    - extra
    - codehilite
    - smarty
    - toc
    - wikilinks
    - admonition
    - pyembed.markdown

plugins:
    - search:
        lang: ['en']
        prebuild_index: False


extra:
  social:
    - type: 'globe'
      link: 'https://turris.cz'
    - type: 'gitlab'
      link: 'https://gitlab.labs.nic.cz/turris'
    - type: 'github'
      link: 'https://github.com/CZ-NIC'
    - type: 'twitter'
      link: 'https://twitter.com/turris_cz'

nav:
- Introduction: 'index.md'
- Basics:
    - First setup:
        - 'MOX': 'basics/first-setup/mox_first_setup.md'
    - Data Collection:
        - 'Why?': 'basics/collect/why.md'
        - 'What we collect': 'basics/collect/data.md'
        - 'How to setup?': 'basics/collect/howto.md'
    - Foris:
        - 'Secure access': 'basics/foris-https/https.md'
        - LAN: 'basics/foris-lan/foris-lan.md'
        - WAN: 'basics/foris-wan/foris_wan.md'
        - DNS: 'basics/foris-dns/foris-dns.md'
        - 'Guest network': 'basics/guest-network/guest-network.md'
        - 'Netmetr': 'basics/apps/netmetr.md'
        - 'Storage': 'basics/storage-plugin/storage-plugin.md'
    - Applications:
        - 'LXC': 'geek/lxc/lxc.md'
        - 'Sentinel': 'basics/apps/sentinel.md'
- Advanced:
    - 'Netboot': 'basics/apps/netboot.md'
    - 'OpenVPN': 'basics/openvpn/openvpn.md'
    - 'Schnapps': 'geek/schnapps/schnapps.md'
- Hardware:
    - MOX:
        - About: 'hw/mox/intro.md'
        - Sets:
            - 'Start': 'hw/mox/sets/start.md'
            - 'Pocket Wi-Fi': 'hw/mox/sets/pocketwifi.md'
            - 'Power Wi-Fi': 'hw/mox/sets/powerwifi.md'
            - 'Classic': 'hw/mox/sets/classic.md'
        - Modules:
            - 'MOX A (Basic)': 'hw/mox/modules/a.md'
            - 'MOX B (Extension)': 'hw/mox/modules/b.md'
            - 'MOX C (Ethernet)': 'hw/mox/modules/c.md'
            - 'MOX D (SFP)': 'hw/mox/modules/d.md'
            - 'MOX E (Super Ethernet)': 'hw/mox/modules/e.md'
            - 'MOX F (USB)': 'hw/mox/modules/f.md'
            - 'MOX G (Super Extension)': 'hw/mox/modules/g.md'
        - Add-ons: 'hw/mox/addons.md'
        - Hardware details: 'hw/mox/hw.md'
- Troubleshooting:
    - Rescue modes:
        - 'MOX': 'hw-spec/mox/mox_rescue_modes.md'
        - 'Omnia': 'hw-spec/omnia_rescue_modes.md'
    - 'MOX MicroSD card': 'hw-spec/mox/mox_microsd.md'
    - Serial: 'hw/serial.md'

