site_name: Turris Documentation
site_description: Official Turris documentation for both hardware and software
site_author: CZ.NIC z.s.p.o.
copyright: CC-BY-SA-4.0


theme:
    name: 'material'
    logo: '/theme/turris-logo.svg'
    favicon: '/theme/favicon.ico'
    font: false
    language: 'en'
    scheme: preference
    features:
      - navigation.instant
    static_templates:
      - 404.html

extra_css:
  - theme/turris.css


markdown_extensions:
    - markdown_include.include:
        base_path: docs
    - admonition
    - cell_row_span
    - extra
    - pymdownx.details
    - pymdownx.superfences
    - codehilite
    - markdown_jinja:
        fs_loader_dir: 'docs'
    - smarty
    - toc:
        permalink: '⚓︎'
    - wikilinks
    - admonition
    - pyembed.markdown

plugins:
    - search:
        lang: ['en']
        prebuild_index: False
    - git-revision-date:
        modify_md: False


extra:
  social:
    - icon: 'fontawesome/solid/globe'
      link: 'https://turris.cz'
    - icon: 'fontawesome/brands/gitlab'
      link: 'https://gitlab.nic.cz/turris'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/CZ-NIC'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/turris_cz'

nav:
- Introduction: 'index.md'
- First setup:
    - 'MOX': 'basics/first-setup/mox_first_setup.md'
    - 'Turris 1.X and Omnia': 'basics/first-setup/simple_setup.md'
- Software:
    - Data Collection: 'basics/collect.md'
    - Foris:
        - 'Secure access': 'basics/foris/https/https.md'
        - LAN: 'basics/foris/lan/foris-lan.md'
        - WAN: 'basics/foris/wan/foris_wan.md'
        - DNS: 'basics/foris/dns/foris-dns.md'
        - 'Guest network': 'basics/foris/guest-network/guest-network.md'
        - 'Storage': 'basics/foris/storage-plugin/storage-plugin.md'
    - reForis:
        - About: 'basics/reforis/intro.md'
        - Screenshots: 'basics/reforis/screenshots/reforis.md'
    - LuCI:
        - Introduction: basics/luci/luci.md
        - Static IP: basics/luci/static_dhcp/static_dhcp.md
    - Applications:
        - 'Netmetr': 'basics/apps/netmetr.md'
        - 'Nextcloud': 'geek/nextcloud/nextcloud.md'
        - 'OpenVPN': 'basics/apps/openvpn/openvpn.md'
        - 'PaKon': 'basics/apps/pakon.md'
        - 'Sentinel': 'basics/apps/sentinel.md'
    - Advanced:
        - 'LXC': 'geek/lxc/lxc.md'
        - 'Netboot': 'basics/apps/netboot.md'
        - 'Schnapps': 'geek/schnapps/schnapps.md'
    - 'OS versions':
        - Versions: 'basics/tos_versions.md'
        - Changelog: 'basics/changelog.md'
        - 'Early access': 'geek/testing.md'
        - '3.x migration': 'geek/tos3_migration.md'
- Hardware:
    - Models: 'basics/models.md'
    - MOX:
        - About: 'hw/mox/intro.md'
        - Sets:
            - 'Start': 'hw/mox/sets/start.md'
            - 'Pocket Wi-Fi': 'hw/mox/sets/pocketwifi.md'
            - 'Power Wi-Fi': 'hw/mox/sets/powerwifi.md'
            - 'Classic': 'hw/mox/sets/classic.md'
        - Modules:
            - 'MOX A (Basic)': 'hw/mox/modules/a.md'
            - 'MOX B (Extension)': 'hw/mox/modules/b.md'
            - 'MOX C (Ethernet)': 'hw/mox/modules/c.md'
            - 'MOX D (SFP)': 'hw/mox/modules/d.md'
            - 'MOX E (Super Ethernet)': 'hw/mox/modules/e.md'
            - 'MOX F (USB)': 'hw/mox/modules/f.md'
            - 'MOX G (Super Extension)': 'hw/mox/modules/g.md'
        - Add-ons: 'hw/mox/addons.md'
        - Hardware details: 'hw/mox/hw.md'
    - Omnia:
        - About: 'hw/omnia/omnia.md'
        - Revisions: 'hw/omnia/revisions.md'
    - Shield:
        - About: 'hw/shield/shield.md'
        - Screenshots: 'hw/shield/screenshots.md'
    - Turris 1.X: 'hw/turris-1x/turris-1x.md'
- Troubleshooting:
    - 'Common errors': 'basics/common_errors.md'
    - Rescue modes:
        - 'MOX': 'hw/mox/rescue_modes.md'
        - 'Omnia': 'hw/omnia/rescue_modes.md'
    - MOX MicroSD: 'hw/mox/microsd.md'
    - 'Serial connection': 'hw/serial.md'
    - 'Serial boot':
        - 'MOX': 'hw/mox/serial-boot.md'
        - 'Omnia': 'hw/omnia/serial-boot.md'
    - Support: 'basics/support.md'
